name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Check
        run: yarn check-all
